version: '3.3'
services:
  java:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    command: sh run.sh
    ports:
      - "8080:8080"
      - "35729:35729"
      - "5005:5005"